### PR TITLE
Added (another) Metal version with various features

### PR DESCRIPTION
**Pull request by hyperjeff**
Let me know what you think! It's quick and lets you explore and save various values of F and k.

Worth noting: Building it for running (vs debugging) produces a much more performant app, much smoother than running it directly from Xcode in debug mode.

### CODE REVIEW

**Comment by wigging** [comment]
Thank you for submitting this and it runs without any issues on my laptop. I can definitely learn a lot from this example.

Regarding your note about building the project... How do I build the project for running vs debugging? Are you referring to the Debug and Release modes in the Build Settings?

There's a Swift subsection in the Examples section of the README. Please add a screenshot of the app and a brief paragraph explaining the app and associated Xcode project.

**Comment by hyperjeff** [comment]
oK, good idea to add README, will do.

**Comment by hyperjeff** [comment]
Ok, readme info updated ✔︎

**Comment by wigging** [comment]
Looks good. I'll go ahead and merge it. 👍

**Pull request merged**
